template: Updated The Flasher to Anykernel V3

diff --git a/template/META-INF/com/google/android/update-binary b/template/META-INF/com/google/android/update-binary
--- a/template/META-INF/com/google/android/update-binary
+++ b/template/META-INF/com/google/android/update-binary
@@ -1,10 +1,13 @@
 #!/sbin/sh
-# AnyKernel2 Backend
+# AnyKernel3 Backend (DO NOT CHANGE)
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
 ZIPFILE="$3";
-DIR=`dirname "$ZIPFILE"`;
+DIR=$(dirname "$ZIPFILE");
+
+test "$home" || home=/tmp/anykernel;
+parent=$(dirname $home);
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -13,190 +16,203 @@ ui_print() {
   done;
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
-file_getprop() { grep "^$2=" "$1" | cut -d= -f2; }
-if [ ! "$(getprop 2>/dev/null)" ]; then
-  getprop() {
-    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
-    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
-    test "$propval" && echo "$propval" || echo "";
-  }
-fi;
-cleanup() { rm -rf /tmp/anykernel; }
+file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
+int2ver() {
+  if [ "$1" -eq "$1" ] 2>/dev/null; then 
+    echo "$1.0.0";
+  elif [ ! "$(echo "$1" | $bb cut -d. -f3)" ]; then
+    echo "$1.0";
+  else
+    echo "$1";
+  fi;
+}
+cleanup() {
+  cd $parent;
+  rm -rf $home;
+}
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-    
-      ui_print "Creating debugging archive in zip directory...";
-      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
+      ui_print " " "Creating debugging archive in zip directory...";
+      $bb tar -czvf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $parent/*;
     ;;
   esac;
+}
+is_mounted() { $bb mount | $bb grep " $1 "; }
+unmount_all() {
+  ($bb umount /system;
+  if [ -d /system_root -a ! -f /system/build.prop ]; then
+    $bb umount /system_root;
+  fi;
+  $bb umount /system;
+  $bb umount /vendor;
+  $bb umount /data) 2>/dev/null;
 }
 abort() {
   ui_print "$*";
   debugging;
-  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
+  if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
-  umount /system;
-  umount /vendor 2>/dev/null;
-  umount /data 2>/dev/null;
+  unmount_all;
   exit 1;
 }
 
 show_progress 1.34 4;
 ui_print " ";
 cleanup;
-mkdir -p /tmp/anykernel/bin;
-cd /tmp/anykernel;
+mkdir -p $home/bin;
+cd $home;
 unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
+if [ $? != 0 -o ! "$(ls tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
-bb=/tmp/anykernel/tools/busybox;
+bb=$home/tools/busybox;
 chmod 755 $bb;
-$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+$bb chmod -R 755 tools bin;
+$bb --install -s bin;
+if [ $? != 0 -o -z "$(ls bin)" ]; then
+  abort "Busybox setup failed. Aborting...";
+fi;
 
-if [ -f /tmp/anykernel/banner ]; then
+if [ -f banner ]; then
   while IFS='' read -r line || $bb [[ -n "$line" ]]; do
     ui_print "$line";
-  done < /tmp/anykernel/banner;
-  ui_print " ";
-  ui_print " ";
+  done < banner;
+  ui_print " " " ";
 fi;
 
-ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
-if [ -f /tmp/anykernel/version ]; then
+ui_print "$(file_getprop anykernel.sh kernel.string)";
+if [ -f version ]; then
   ui_print " ";
-  ui_print "$(cat /tmp/anykernel/version)";
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < version;
   ui_print " ";
 fi;
-ui_print " ";
-ui_print " ";
-ui_print " ";
+ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
 
-umount /system 2>/dev/null;
-umount /vendor 2>/dev/null;
-mount -o ro -t auto /system;
-mount -o ro -t auto /vendor 2>/dev/null;
-mount /data 2>/dev/null;
-test -f /system/system/build.prop && root=/system;
+unmount_all;
+if [ ! "$(is_mounted /system)" ]; then
+  $bb mount -o ro -t auto /system;
+fi;
+($bb mount -o ro -t auto /vendor;
+$bb mount /data) 2>/dev/null;
+if [ -f /system/system/build.prop ]; then
+  $bb umount /system;
+  ($bb umount /system;
+  mkdir /system_root) 2>/dev/null;
+  $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+  $bb mount -o bind /system_root/system /system;
+fi;
+savedpath="$LD_LIBRARY_PATH";
+savedpre="$LD_PRELOAD";
+unset LD_LIBRARY_PATH;
+unset LD_PRELOAD;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
+if [ ! "$(getprop 2>/dev/null)" ]; then
+  getprop() {
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
+    test "$propval" && echo "$propval" || echo "";
+  }
+elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.product 2>/dev/null)" ]; then
+  getprop() {
+    ($(which getprop) | $bb grep "$1" | $bb cut -d[ -f3 | $bb cut -d] -f1) 2>/dev/null;
+  }
+fi;
+
+if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking device...";
-  for i in 1 2 3 4 5; do
-    testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
-    if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
+  device="$(getprop ro.product.device)";
+  product="$(getprop ro.build.product)";
+  for testname in $(file_getprop anykernel.sh 'device.name.*'); do
+    if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
       ui_print "$testname";
       match=1;
+      break;
     fi;
   done;
   ui_print " ";
-  if [ "$match" != 1 ]; then
+  if [ ! "$match" ]; then
     abort "Unsupported device. Aborting...";
   fi;
 fi;
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print "===================================================";
-ui_print "                                                   ";
-ui_print "  ::::    ::::   ::::::::  :::    ::: ::::    :::  ";
-ui_print "  +:+:+: :+:+:+ :+:    :+: :+:    :+: :+:+:   :+:  ";
-ui_print "  +:+ +:+:+ +:+ +:+    +:+ +:+    +:+ :+:+:+  +:+  ";
-ui_print "  +#+  +:+  +#+ +#+    +:+ +#+    +:+ +#+ +:+ +#+  ";
-ui_print "  +#+       +#+ +#+    +#+ +#+    +#+ +#+  +#+#+#  ";
-ui_print "  #+#       #+# #+#    #+# #+#    #+# #+#   #+#+#  ";
-ui_print "  ###       ###  ########   ########  ###    ####  ";
-ui_print "                                                   ";
-ui_print "----------------------KERNEL-----------------------";
-ui_print "                                                                                               ";
-ui_print "-----A Kernel by Mountaser Halak for the Mi A1-----";
-ui_print "===================================================";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-for i in $($bb --list); do
-  $bb ln -s $bb /tmp/anykernel/bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
+supported_ver="$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]')";
+if [ "$supported_ver" ]; then
+  ui_print "Checking Android version...";
+  android_ver="$(file_getprop /system/build.prop ro.build.version.release)";
+  if [ "$(echo $supported_ver | $bb grep -)" ]; then
+    lo_ver=$(echo $supported_ver | $bb cut -d- -f1);
+    hi_ver=$(echo $supported_ver | $bb cut -d- -f2);
+    if [ "$(echo -e "$(int2ver $hi_ver)\n$(int2ver $lo_ver)\n$(int2ver $android_ver)" | $bb sort -g | $bb grep -n "$(int2ver $android_ver)" | $bb grep '^2:')" ]; then
+      supported=1;
+    fi;
+  else
+    for ver in $(echo $supported_ver | $bb sed 's;,; ;g'); do
+      if [ "$(int2ver $ver)" == "$(int2ver $android_ver)" ]; then
+        supported=1;
+        break;
+      fi;
+    done;
+  fi;
+  if [ "$supported" ]; then
+    ui_print "$android_ver" " ";
+  else
+    ui_print " ";
+    abort "Unsupported Android version. Aborting...";
+  fi;
 fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
-if [ $? != "0" ]; then
+
+ui_print "Installing...";
+core=$($bb grep -oE 'ak.*core.sh' anykernel.sh);
+test -f tools/$core || $bb ln -s $home/tools/ak*-core.sh $home/tools/$core;
+PATH="$home/bin:$PATH" home=$home $bb ash anykernel.sh $2;
+if [ $? != 0 ]; then
   abort;
 fi;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
-  ui_print " ";
-  ui_print "Pushing modules...";
-  mount -o rw,remount -t auto /system;
-  mount -o rw,remount -t auto /vendor 2>/dev/null;
-  cd /tmp/anykernel/modules;
+if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
+  ui_print " " "Pushing modules...";
+  $bb mount -o rw,remount -t auto /system;
+  $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
+  cd $home/modules;
   for module in $(find . -name '*.ko'); do
-    if [ ! -e /$module ]; then
+    modtarget=$(echo $module | $bb cut -c2-);
+    if [ ! -e $modtarget ]; then
       case $module in
-        */vendor/*) mod=vendor;;
-        *) mod=system;;
+        */vendor/*) modcon=vendor;;
+        *) modcon=system;;
       esac;
     fi;
-    $bb cp -rLf $module /$module;
-    $bb chown 0:0 /$module;
-    $bb chmod 644 /$module;
-    if [ "$mod" ]; then
-      chcon "u:object_r:${mod}_file:s0" /$module;
+    if [ "$(is_mounted $modtarget)" ]; then
+      $bb mount -o rw,remount -t auto $modtarget;
+    fi;
+    mkdir -p $(dirname $modtarget);
+    $bb cp -rLf $module $modtarget;
+    $bb chown 0:0 $modtarget;
+    $bb chmod 644 $modtarget;
+    if [ "$modcon" ]; then
+      chcon "u:object_r:${modcon}_file:s0" $modtarget;
+    fi;
+    if [ "$(is_mounted $modtarget)" ]; then
+      $bb mount -o ro,remount -t auto $modtarget;
     fi;
   done;
-  cd /tmp/anykernel;
-  mount -o ro,remount -t auto /system;
-  mount -o ro,remount -t auto /vendor 2>/dev/null;
+  cd $home;
+  $bb mount -o ro,remount -t auto /system;
+  $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
 
 debugging;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
+if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-umount /system;
-umount /vendor 2>/dev/null;
-umount /data 2>/dev/null;
-ui_print " ";
-ui_print " ";
-ui_print "Done!";
+test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
+test "$savedpre" && export LD_PRELOAD="$savedpre";
+
+unmount_all;
+
+ui_print " " " " "Done!";
